/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Grafico;

import javax.swing.JOptionPane;

/**
 *
 * @author Rafa
 */
public class Registro extends javax.swing.JFrame {

    /**
     * Creates new form Registro
     */
    public Registro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        Titulo = new javax.swing.JPanel();
        Inicio_Titulo = new javax.swing.JLabel();
        Fondo_ventana = new javax.swing.JPanel();
        Cedenciales = new javax.swing.JLabel();
        Fondo_LogIn = new javax.swing.JPanel();
        Verificar = new javax.swing.JButton();
        Usuario = new javax.swing.JLabel();
        Pass = new javax.swing.JLabel();
        Usuario_data = new javax.swing.JTextField();
        Usuario_pass = new javax.swing.JPasswordField();
        Panel_inferior = new javax.swing.JPanel();
        Ocultar = new javax.swing.JButton();
        Ver = new javax.swing.JButton();
        ImgDeFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 102, 255));
        setResizable(false);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setBackground(new java.awt.Color(204, 204, 255));

        Inicio_Titulo.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        Inicio_Titulo.setText("Inicio de sesion");

        javax.swing.GroupLayout TituloLayout = new javax.swing.GroupLayout(Titulo);
        Titulo.setLayout(TituloLayout);
        TituloLayout.setHorizontalGroup(
            TituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Inicio_Titulo)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        TituloLayout.setVerticalGroup(
            TituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TituloLayout.createSequentialGroup()
                .addGap(0, 3, Short.MAX_VALUE)
                .addComponent(Inicio_Titulo))
        );

        jPanel4.add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 260, 50));

        Fondo_ventana.setBackground(new java.awt.Color(204, 204, 255));
        Fondo_ventana.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Cedenciales.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        Cedenciales.setText("Ingrese sus credenciales");

        Fondo_LogIn.setBackground(new java.awt.Color(153, 153, 153));
        Fondo_LogIn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Verificar.setBackground(new java.awt.Color(255, 255, 255));
        Verificar.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        Verificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Grafico/Imagenes/Verificar.png"))); // NOI18N
        Verificar.setText("Verificar");
        Verificar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Verificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VerificarMouseClicked(evt);
            }
        });
        Verificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerificarActionPerformed(evt);
            }
        });

        Usuario.setText("Usuario:");

        Pass.setText("Contraseña:");

        javax.swing.GroupLayout Fondo_LogInLayout = new javax.swing.GroupLayout(Fondo_LogIn);
        Fondo_LogIn.setLayout(Fondo_LogInLayout);
        Fondo_LogInLayout.setHorizontalGroup(
            Fondo_LogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Fondo_LogInLayout.createSequentialGroup()
                .addGroup(Fondo_LogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Fondo_LogInLayout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(Usuario))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Fondo_LogInLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Pass)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Fondo_LogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Usuario_data, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                    .addComponent(Usuario_pass))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Fondo_LogInLayout.createSequentialGroup()
                .addGap(0, 147, Short.MAX_VALUE)
                .addComponent(Verificar, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(125, 125, 125))
        );
        Fondo_LogInLayout.setVerticalGroup(
            Fondo_LogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Fondo_LogInLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(Fondo_LogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Usuario)
                    .addComponent(Usuario_data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(Fondo_LogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Pass)
                    .addComponent(Usuario_pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(Verificar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout Fondo_ventanaLayout = new javax.swing.GroupLayout(Fondo_ventana);
        Fondo_ventana.setLayout(Fondo_ventanaLayout);
        Fondo_ventanaLayout.setHorizontalGroup(
            Fondo_ventanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Fondo_ventanaLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(Cedenciales)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Fondo_ventanaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Fondo_LogIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        Fondo_ventanaLayout.setVerticalGroup(
            Fondo_ventanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Fondo_ventanaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Cedenciales)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Fondo_LogIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jPanel4.add(Fondo_ventana, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 73, 480, 310));

        Panel_inferior.setBackground(new java.awt.Color(204, 204, 255));
        Panel_inferior.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Ocultar.setBackground(new java.awt.Color(255, 255, 255));
        Ocultar.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        Ocultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Grafico/Imagenes/Ocultar.png"))); // NOI18N
        Ocultar.setText("Ocultar");
        Ocultar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Ocultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OcultarMouseClicked(evt);
            }
        });
        Ocultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OcultarActionPerformed(evt);
            }
        });

        Ver.setBackground(new java.awt.Color(255, 255, 255));
        Ver.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        Ver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Grafico/Imagenes/Ver.png"))); // NOI18N
        Ver.setText("Ver");
        Ver.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Ver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VerMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Panel_inferiorLayout = new javax.swing.GroupLayout(Panel_inferior);
        Panel_inferior.setLayout(Panel_inferiorLayout);
        Panel_inferiorLayout.setHorizontalGroup(
            Panel_inferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_inferiorLayout.createSequentialGroup()
                .addContainerGap(217, Short.MAX_VALUE)
                .addComponent(Ocultar, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(Ver, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(182, 182, 182))
        );
        Panel_inferiorLayout.setVerticalGroup(
            Panel_inferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_inferiorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_inferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Ver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Ocultar, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel4.add(Panel_inferior, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 760, 90));

        ImgDeFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Grafico/Imagenes/pxfuel.jpg"))); // NOI18N
        jPanel4.add(ImgDeFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 782, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void VerificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerificarActionPerformed
        
    }//GEN-LAST:event_VerificarActionPerformed

    private void OcultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OcultarActionPerformed
     
    }//GEN-LAST:event_OcultarActionPerformed

    private void VerificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VerificarMouseClicked

    //comentario agregado    
    if (Usuario_data.getText().isEmpty() || Usuario_pass.getText().isEmpty() ){ // tenemos que controlar que ambos TB tengan datos, si alguno está vacio, no puede ingresar
        JOptionPane.showMessageDialog(null, "Complete la información solicitada...","Entrada Inválida",JOptionPane.WARNING_MESSAGE);
    }else{        
        //Si completó la información, la corrobora para ver si coincide con los autorizados
         String usuario="alumno@ulp.edu.ar";
         String pass="12345678";
         if (Usuario_data.getText().equalsIgnoreCase(usuario)){

             //El Usuario es el autorizado, ahora controlamos la password
            if (Usuario_pass.getText().equalsIgnoreCase(pass)){
               //El Usuario es el autorizado, la password es la indicada
               JOptionPane.showMessageDialog(null, "AUTORIZADO..","Bienvenido!",JOptionPane.INFORMATION_MESSAGE);
               dispose(); 
            }else{
               JOptionPane.showMessageDialog(null, "Acceso NO AUTORIZADO","Verificación de Acceso al Sistema",JOptionPane.WARNING_MESSAGE);
            }

         }else{
            
             JOptionPane.showMessageDialog(null, "Acceso NO AUTORIZADO","Verificación de Acceso al Sistema",JOptionPane.WARNING_MESSAGE);

         }
    
    }    

        
    }//GEN-LAST:event_VerificarMouseClicked

    private void OcultarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OcultarMouseClicked
       
        Usuario_pass.setEchoChar('*');
        
    }//GEN-LAST:event_OcultarMouseClicked

    private void VerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VerMouseClicked
        Usuario_pass.setEchoChar((char)0);
    }//GEN-LAST:event_VerMouseClicked

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cedenciales;
    private javax.swing.JPanel Fondo_LogIn;
    private javax.swing.JPanel Fondo_ventana;
    private javax.swing.JLabel ImgDeFondo;
    private javax.swing.JLabel Inicio_Titulo;
    private javax.swing.JButton Ocultar;
    private javax.swing.JPanel Panel_inferior;
    private javax.swing.JLabel Pass;
    private javax.swing.JPanel Titulo;
    private javax.swing.JLabel Usuario;
    private javax.swing.JTextField Usuario_data;
    private javax.swing.JPasswordField Usuario_pass;
    private javax.swing.JButton Ver;
    private javax.swing.JButton Verificar;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
